import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Navbar component
const Navbar = () => {
  return (
    <nav className="bg-gray-900 text-white p-4 shadow-md">
      <div className="max-w-7xl mx-auto flex justify-between items-center">
        <div className="text-3xl font-extrabold text-yellow-400">
          <Link href="/" className="hover:text-yellow-500 transition-all duration-300">
           Shadow Shop 
          </Link>
        </div>
        <ul className="flex space-x-8">
          <li>
            <Link href="/anis" className="text-lg font-medium hover:text-yellow-400 transition-all duration-300">
              Home
            </Link>
          </li>
          <li>
            <Link href="/blogs" className="text-lg font-medium hover:text-yellow-400 transition-all duration-300">
              Blogs
            </Link>
          </li>
          <li>
            <Link href="/contacts" className="text-lg font-medium hover:text-yellow-400 transition-all duration-300">
              Contact
            </Link>
          </li>
          <li>
            <Link href="/login" className="text-lg font-medium hover:text-yellow-400 transition-all duration-300">
              Login
            </Link>
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar Component */}
        <Navbar />
        {/* Main Content */}
        <main className="pt-8">{children}</main>
      </body>
    </html>
  );
}
